// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSwZSWxa-HjGwuyz-RSPs5XGG6hPnKT7w',
    appId: '1:1076114266861:web:d3a0ce6aacceedd5e84ae4',
    messagingSenderId: '1076114266861',
    projectId: 'mtouch-machine',
    authDomain: 'mtouch-machine.firebaseapp.com',
    storageBucket: 'mtouch-machine.appspot.com',
    measurementId: 'G-ZGSZ506S41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWYCsIc_9Jma5IBv4Qa5y7IU2MkxZWFDY',
    appId: '1:1076114266861:android:b8c0560afd65dab7e84ae4',
    messagingSenderId: '1076114266861',
    projectId: 'mtouch-machine',
    storageBucket: 'mtouch-machine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1slVK_v4WPwsJudbuiFlSSIEXbMnoi9Q',
    appId: '1:1076114266861:ios:23812ebd1fa44eabe84ae4',
    messagingSenderId: '1076114266861',
    projectId: 'mtouch-machine',
    storageBucket: 'mtouch-machine.appspot.com',
    iosBundleId: 'com.example.mtouchMachineTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1slVK_v4WPwsJudbuiFlSSIEXbMnoi9Q',
    appId: '1:1076114266861:ios:55331ba2a98f8bede84ae4',
    messagingSenderId: '1076114266861',
    projectId: 'mtouch-machine',
    storageBucket: 'mtouch-machine.appspot.com',
    iosBundleId: 'com.example.mtouchMachineTest.RunnerTests',
  );
}
